###
#   Database Settings
###
spring:
  datasource:
    #url: jdbc:h2:file:C:/Project/db/try_spr_hib;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    # подключение во время транзакции
    url: jdbc:h2:file:C:/Project/db/try_spr_hib;MVCC=FALSE;MV_STORE=FALSE;LOCK_MODE=0;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    # подключение к БД в памяти
    #url: jdbc:h2:mem:mydatabase
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      #ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

###
#   H2 Settings
###
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
